# channel.py
CHANNELS = [
    '@videy_viral',
    '@videy_bokep_indo',

    '@film_jav_sub_indoo',
    '@njavtv_japan_jav',
    '@hot_japan_jav',
    '@japan_av_jav',
    '@bokep_jepang_jav_2025',
    '@jav_sub_indo2025',
    '@jav_terbaru_2025',
    '@jav_terbaruu',
    '@bokep_jav_2025',
    '@bokep_jav_subtitle_indonesia',

    '@viral_ayam_kampus_bokep_indo',
    '@bokep_mahasiswi_viral',
    '@bokep_indo_mahasiswa_kampus',
    '@film_bokep_sekolah_full',
    '@bokep_sma_chindo',
    '@bokep_indo_guru_vs_murid',
    '@viral_smk_terbaruu',
    '@bokep_viral_sma10',
    '@bokep_indo_sma_terbaruu',
    '@bokep_sma_sama_guru',

    '@film_bokep_siswi_smp',
    '@bokep_smp_pramuka',
    '@bokep_smp_terbaru',
    '@bokep_viral_smp_dengan_pacar',
    '@bokep_chindo_smp_viral',
    '@bokep_indo_masih_pakai_seragam',
    '@bokep_indo_viral_smp_vs_guru',
    '@bokep_viral_pakai_tanktop',
    '@bokep_indo_smp_kacamata',
    '@bokep_viral_bocil_smp',

    '@videy_viral_bokep_video',
    '@bokep_videy_indo_terbaru',
    '@nonton_videy_bokep_terbaru',
    '@videy_bokep_terbaru',
    '@bokep_chindo_videy',
    '@bokep_videy_chindo',
    '@bokep_videy_indo_2025',
    '@bokep_indo_videy',
    '@bokep_videy_terbaru',
    '@videy_viral_indo',

    '@xhamster_bokep_indo',
    '@xnxx_bokep_indo',
    '@asupanbokep10',
    '@bokep_indo10',
    '@viral_bokep_indoo',
    '@film_bokep_indo10',
    '@bokep_indo_viral_10',
    '@bokep_indo_video10',
    '@bokep_indo_viral10',
    '@bokep_indo_threesome_terbaru',


    '@azizah_istri_arhan_pratama_xx',
    '@video_azizah_zize_viral_xx',
    '@azizah_viral_istri_arhan_xx',
    '@TeraboxUpdateIndo',
    '@TeraboxBokepIndonesia_xx',
    '@TeraboxViralTerbaru_xx',
    '@TeraboxBokepTerbaru_xx',
    '@TeraboxYangLagiViral',
    '@TeraboxVideoViral2024',

    '@video_azizah_salsha_virall',
    '@istri_arhan_viral_xx',
    '@VideyViralTerbaru',
    '@VideyViral2024',
    '@VideyBokepIndo',
    '@VideyBokepIndoTerbaru',
    '@VideyTiktokIndo',
    '@VideyTiktokViral',
    '@VideyIndonesia',
    '@azizah_shalsa_video_virall',

    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    
]
