# channel.py
CHANNELS = [
    '@videy_viral',
    '@videy_bokep_indo',

    '@film_jav_sub_indoo',
    '@njavtv_japan_jav',
    '@hot_japan_jav',
    '@japan_av_jav',
    '@bokep_jepang_jav_2025',
    '@jav_sub_indo2025',
    '@jav_terbaru_2025',
    '@jav_terbaruu',
    '@bokep_jav_2025',
    '@bokep_jav_subtitle_indonesia',

    '@viral_ayam_kampus_bokep_indo',
    '@bokep_mahasiswi_viral',
    '@bokep_indo_mahasiswa_kampus',
    '@film_bokep_sekolah_full',
    '@bokep_sma_chindo',
    '@bokep_indo_guru_vs_murid',
    '@viral_smk_terbaruu',
    '@bokep_viral_sma10',
    '@bokep_indo_sma_terbaruu',
    '@bokep_sma_sama_guru',

    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',

    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',

    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    'TES',
    
]
